<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SyncAudio</RootNamespace>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Content Update="wwwroot\audio\track.flac">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\audio\" />
  </ItemGroup>
</Project>
