<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SyncAudio.Core</RootNamespace>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Microsoft.Extensions.Hosting" />
    <Using Include="Microsoft.AspNetCore.Hosting" />
    <Using Include="Microsoft.AspNetCore.Http" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Minio" Version="6.0.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Stateless" Version="5.16.0" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SyncAudio.Tests" />
  </ItemGroup>
</Project>
